In [32]:
import pandas as pd

In [33]:
sbux = pd.read_csv('BUS303_Signature_Term_Project_Starbucks_Beverage_Menu.csv')

In [34]:
sbux.to_csv(r'C:\Users\natalyrojas\cleaned_starbucks_data.csv',index=False)

In [35]:
sbux.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0

In [36]:
sbux = sbux.dropna(how='all')

In [37]:
sbux.isnull().sum()

Product_Name           0
Size                   0
Milk                   0
Whip                   0
Serving_Size_ml        0
Calories               0
Total_Fat_g            0
Saturated_Fat_g        1
Trans_Fat_g            0
Cholesterol_mg         0
Sodium_mg              0
Carbohydrates_g        0
Dietary_Fiber_g        0
Sugar_g                0
Protein_g              0
Vitamin_A_%DV          0
Vitamin_C_%DV          0
Calcium_%DV            0
Iron_%DV               0
Caffiene_milligrams    0
dtype: int64

In [38]:
sbux.dtypes

Product_Name               str
Size                       str
Milk                       str
Whip                       str
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                    str
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [39]:
sbux.iloc[:,:]

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [40]:
sbux.iloc[:,:].dtypes

Product_Name               str
Size                       str
Milk                       str
Whip                       str
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                    str
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [42]:
sbux['Sugar_g'] = pd.to_numeric(sbux['Sugar_g'], errors='coerce')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [43]:
sbux['Sugar_g'] = sbux['Sugar_g'].replace('zero', '0').astype(float)

In [44]:
sbux.dtypes

Product_Name               str
Size                       str
Milk                       str
Whip                       str
Serving_Size_ml        float64
Calories               float64
Total_Fat_g            float64
Saturated_Fat_g        float64
Trans_Fat_g            float64
Cholesterol_mg         float64
Sodium_mg              float64
Carbohydrates_g        float64
Dietary_Fiber_g        float64
Sugar_g                float64
Protein_g              float64
Vitamin_A_%DV          float64
Vitamin_C_%DV          float64
Calcium_%DV            float64
Iron_%DV               float64
Caffiene_milligrams    float64
dtype: object

In [45]:
sbux.info()

<class 'pandas.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   str
 1   Size                 1204 non-null   str
 2   Milk                 1204 non-null   str
 3   Whip                 1204 non-null   str
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.4 KB

In [47]:
df2 = sbux.dropna(subset=['Saturated_Fat_g'])

In [48]:
df2.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   str
 1   Size                 1203 non-null   str
 2   Milk                 1203 non-null   str
 3   Whip                 1203 non-null   str
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1202 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [53]:
sbux=df2.rename(columns={'Caffiene_milligrams':'Caffeine_milligrams'})

In [54]:
sbux.info()

<class 'pandas.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   str
 1   Size                 1203 non-null   str
 2   Milk                 1203 non-null   str
 3   Whip                 1203 non-null   str
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1202 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffeine_milligrams  1203 non-null   float64
dtypes: float64(16), str(4)
memory usage: 249.2 KB

In [51]:
sbux.to_csv('sbux.csv', index=False)

In [52]:
sbux_check = pd.read_csv('sbux.csv')
sbux_check.head()

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,NaN,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0

In [55]:
import pandas as pd
dnkn = pd.read_csv('BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv')

In [56]:
print(dnkn.head())

           Category                                 Item Calories  \
0  Cold Brew Coffee              Cold Brew Coffee, Large        5
1  Cold Brew Coffee             Cold Brew Coffee, Medium        5
2  Cold Brew Coffee              Cold Brew Coffee, Small        5
3  Cold Brew Coffee   Cold Brew Coffee with Cream, Large      120
4  Cold Brew Coffee  Cold Brew Coffee with Cream, Medium       90

  Total Fat (g) Saturated Fat (g) Trans Fat (g) Cholesterol (mg) Sodium (mg)  \
0             0                 0             0                0          20
1             0                 0             0                0          15
2             0                 0             0                0          10
3            12                 6             0               35          65
4             9               4.5             0               25          45

  Carbs (g) Fiber (g) Sugars (g) Protein (g) Weight Watcher Pnts
0         0         0          0           1                   4
1         0         0          0           0                   5
2         0         0          0           0                   5
3         2         0          2           2                 126
4         1         0          1           2                93.5

In [57]:
print(dnkn.info())

<class 'pandas.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    str
 1   Item                 780 non-null    str
 2   Calories             780 non-null    str
 3   Total Fat (g)        780 non-null    str
 4   Saturated Fat (g)    780 non-null    str
 5   Trans Fat (g)        780 non-null    str
 6   Cholesterol (mg)     780 non-null    str
 7   Sodium (mg)          780 non-null    str
 8   Carbs (g)            780 non-null    str
 9   Fiber (g)            780 non-null    str
 10  Sugars (g)           780 non-null    str
 11  Protein (g)          780 non-null    str
 12  Weight Watcher Pnts  780 non-null    str
dtypes: str(13)
memory usage: 132.8 KB
None

In [58]:
missing_values=dnkn.isnull().sum()
print(missing_values)

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [59]:
duplicate_rows = dnkn.duplicated().sum()
print(duplicate_rows)

1

In [60]:
duplicate_records = dnkn[dnkn.duplicated()]
print(duplicate_records)

       Category                    Item Calories Total Fat (g)  \
760  Sandwiches  Ham and Cheese Rollups      280            13

    Saturated Fat (g) Trans Fat (g) Cholesterol (mg) Sodium (mg) Carbs (g)  \
760                 6             0               40        1050        27

    Fiber (g) Sugars (g) Protein (g) Weight Watcher Pnts
760         1          2          13                 275

In [61]:
unique_counts = dnkn.nunique()
print(unique_counts)

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

In [62]:
category_counts = dnkn['Category'].value_counts()
print(category_counts)

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

In [63]:
descriptive_stats = dnkn.describe(include='all')
print(descriptive_stats)

          Category                    Item Calories Total Fat (g)  \
count          780                     780      780           780
unique          23                     779       87            50
top     Hot Coffee  Ham and Cheese Rollups      170             0
freq            88                       2       38           242

       Saturated Fat (g) Trans Fat (g) Cholesterol (mg) Sodium (mg) Carbs (g)  \
count                780           780              780         780       780
unique                29             5               37         112       120
top                    0             0                0         180        35
freq                 269           755              222          24        30

       Fiber (g) Sugars (g) Protein (g) Weight Watcher Pnts
count        780        780         780                 780
unique         9        122          32                 362
top            0          0           4                   5
freq         508         33          94                  13

In [66]:
columns_to_check = ['Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)', 'Cholesterol (mg)', 'Sodium (mg)', 'Fiber (g)', 'Protein (g)', 'Carbs (g)']
for col in columns_to_check:
    if col in dnkn.columns:
        print(f"\nUnique values in '{col}':")
        print(dnkn[col].unique()[:50])
else:
    print(f"\nColumn '{col}' not found in the DataFrame.")

Unique values in 'Total Fat (g)':
<ArrowStringArray>
[  '0',  '12',   '9',   '6', '4.5',   '3',  '10',  '11',  '28',  '30',  '22',
  '21',  '23',  '14',  '15',  '20',  '19',  '16',  '18',  '25',  '31',  '27',
  '17',  '37',  '40',   '5',   '8',  '35',  '26',  '13',   '7',   ' ',   '4',
   '1', '0.5', '1.5', '2.5',   '2', '3.5',  '42',  '33',  '24',  '36',  '54',
  '29',  '32',  '34',  '52',  '41',  '43']
Length: 50, dtype: str

Unique values in 'Saturated Fat (g)':
<ArrowStringArray>
[  '0',   '6', '4.5',   '3', '3.5', '2.5', '1.5',   '4',  '12',  '14',   '9',
  '10',  '11',   '7',   '5',   '8',  '13',  '18',  '22',  '17',  '15',   ' ',
 '0.5',  '19',  '21',   '1',   '2',  '20',  '16']
Length: 29, dtype: str

Unique values in 'Trans Fat (g)':
<ArrowStringArray>
['0', '1.5', '1', '0.5', ' ']
Length: 5, dtype: str

Unique values in 'Cholesterol (mg)':
<ArrowStringArray>
[  '0',  '35',  '25',  '20',  '15',  '10',  '50',  '30',  '40', '130', '100',
  '70', '105',  '80',  '55',  '<5',   ' ', '125',  '45',  '60', '185', '340',
 '180',  '95',  '65', '190', '360', '195', '265', '175', '220', '120', '200',
 '240', '205', '110', '115']
Length: 37, dtype: str

Unique values in 'Sodium (mg)':
<ArrowStringArray>
[ '20',  '15',  '10',  '65',  '45',  '30',   '5',  '60', '320', '240', '160',
 '300', '310', '470', '450', '420', '150', '340', '290', '400', '390', '440',
 '280', '135', '380', '480', '270', '430', '460', '360', '200', '370', '190',
 '330', '250', '170', '220', '180', '130', '230', '125', '100', '115',  '75',
 '350', '260', '120',   ' ',  '95',  '70']
Length: 50, dtype: str

Unique values in 'Fiber (g)':
<ArrowStringArray>
['0', '1', '2', '3', '4', ' ', '6', '5', '8']
Length: 9, dtype: str

Unique values in 'Protein (g)':
<ArrowStringArray>
[ '1',  '0',  '2', '10',  '7',  '5',  '4',  '6',  '3',  '8', '11',  '9',  ' ',
 '12', '16', '15', '14', '13', '27', '24', '37', '17', '19', '26', '21', '23',
 '18', '28', '33', '22', '25', '20']
Length: 32, dtype: str

Unique values in 'Carbs (g)':
<ArrowStringArray>
[  '0',   '2',   '1',  '37',  '27',  '18', '112',  '84',  '56', '172', '129',
  '86', '113',  '85',  '31',  '44',  '57',  '47',  '63',  '39',  '55',  '48',
  '36',  '58',  '33',  '41',  '34',  '50',  '40',  '21',  '42',  '61',  '43',
  '32',  '52',  '38',  '59',  '35',  '45',  '30',  '49',  '24', '176', '135',
  '95', '175', '134',  '94', '180', '139']
Length: 50, dtype: str

Column 'Carbs (g)' not found in the DataFrame.

In [67]:
dnkn1 = dnkn.copy()
print("DataFrame 'dnkn1' created as a copy of 'dnkn'.")

DataFrame 'dnkn1' created as a copy of 'dnkn'.

In [68]:
food_items = ['Ham and Cheese Rollups', 'Coffee', 'Espresso Drinks', 'Smoothies', 'Iced Coffee', 'Frappés', 'Hot Coffee', 'Hot Chocolate', 'Tea', 'Iced Tea', 'Lemonade', 'Frozen Coffee', 'Frozen Lemonade', 'Frozen Smoothie', 'Frozen Tea', 'Frozen Frappé', 'Frozen Hot Chocolate', 'Frozen Espresso Drink', 'Frozen Iced Coffee', 'Frozen Iced Tea', 'Frozen Lemonade', 'Frozen Smoothie', 'Frozen Tea', 'Frozen Frappé', 'Frozen Hot Chocolate', 'Frozen Espresso Drink', 'Frozen Iced Coffee', 'Frozen Iced Tea', 'Frozen Lemonade', 'Frozen Smoothie', 'Frozen Tea', 'Frozen Frappé', 'Frozen Hot Chocolate', 'Frozen Espresso Drink', 'Frozen Iced Coffee', 'Frozen Iced Tea', 'Frozen Lemonade', 'Frozen Smoothie', 'Frozen Tea', 'Frozen Frappé', 'Frozen Hot Chocolate', 'Frozen Espresso Drink', 'Frozen Iced Coffee', 'Frozen Iced Tea', 'Frozen Lemonade', 'Frozen Smoothie', 'Frozen Tea', 'Frozen Frappé', 'Frozen Hot Chocolate']

In [69]:
dnkn1 = dnkn1[~dnkn1['Category'].isin(food_items)].copy()
print("Food items removed from the 'Category' column.")

Food items removed from the 'Category' column.

In [70]:
duplicate_check_after_removal = dnkn1.duplicated().sum()
print(f"Number of duplicate records after removing food items: {duplicate_check_after_removal}")

Number of duplicate records after removing food items: 1

In [71]:
dnkn2 = dnkn1.copy()

In [72]:
dnkn2['Cholesterol (mg)'] = dnkn2['Cholesterol (mg)'].replace('<5', '5')
print(" '<5' replaced with '5' in 'Cholesterol (mg)' column.")

 '<5' replaced with '5' in 'Cholesterol (mg)' column.

In [84]:
for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = dnkn2[col].str.replace('\xa0', '', regex=False).str.strip()
print(" '\xa0' removed and whitespace stripped from object columns.")

 ' ' removed and whitespace stripped from object columns.

/var/folders/3x/kbwrty4n37l8tk6y31m6scqm0000gn/T/ipykernel_52970/3492928023.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dnkn2.select_dtypes(include='object').columns:

In [82]:
for col in dnkn2.columns:
    if dnkn2[col].dtype == 'object':
        print('\n', col)
        print(dnkn2[col].unique()[:50])

In [85]:
import numpy as np

In [86]:
dnkn2 = dnkn2.replace('', np.nan)
print("Empty strings replaced with NaN values.")

Empty strings replaced with NaN values.

In [87]:
print(dnkn2.isnull().sum())

Category               0
Item                   0
Calories               1
Total Fat (g)          1
Saturated Fat (g)      1
Trans Fat (g)          1
Cholesterol (mg)       1
Sodium (mg)            1
Carbs (g)              1
Fiber (g)              1
Sugars (g)             1
Protein (g)            1
Weight Watcher Pnts    1
dtype: int64

In [88]:
dnkn3 = dnkn2.dropna().copy()
print("NaN values dropped and 'dnkn3' DataFrame created.")

NaN values dropped and 'dnkn3' DataFrame created.

In [89]:
print(dnkn3.isnull().sum())

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [90]:
numeric_columns = ['Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)', 'Cholesterol (mg)', 'Sodium (mg)', 'Fiber (g)', 'Protein (g)', 'Carbs (g)']

In [91]:
for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])

In [92]:
print(" MISSING VALUES ")
print(dnkn3.isnull().sum())

print("\n DATA TYPES ")
print(dnkn3.dtypes)

print("\n DUPLICATE RECORDS ")
print('Duplicates:', dnkn3.duplicated().sum())

print("\n CATEGORY CHECK ")
print(dnkn3['Category'].value_counts())

print("\n SPECIAL VALUE CHECK ")
print("Cholesterol Values:")
print(dnkn3['Cholesterol (mg)'].unique())
print("\nTotal Fat Values:")
print(dnkn3['Total Fat (g)'].unique())

print("\n DATASET SHAPE ")
print(dnkn3.shape)

print("\n SUMMARY STATISTICS ")
print(dnkn3.describe().round(2))

 MISSING VALUES
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

 DATA TYPES
Category                   str
Item                       str
Calories                   str
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)                 str
Protein (g)              int64
Weight Watcher Pnts        str
dtype: object

 DUPLICATE RECORDS
Duplicates: 1

 CATEGORY CHECK
Category
Donuts                87
Hot Latte             63
Iced Latte            63
Sandwiches            55
Hot Macchiato         45
Hot Cappuccino        42
Iced Cappuccino       42
Iced Macchiato        42
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

 SPECIAL VALUE CHECK
Cholesterol Values:
[  0  35  25  20  15  10  50  30  40   5  60  45  55 185 105 340 180  95
  65  70 190 100 360 195 265 175 220 120 200 240 205 110 125 115]

Total Fat Values:
[ 0.  12.   9.   6.   4.5  3.  10.  11.  28.  30.  22.  21.  23.  14.
 15.  20.  19.  16.  18.  25.  31.  27.  17.  37.   8.   4.   1.   0.5
  7.   5.   3.5  2.  13.  26.  42.  33.  24.   2.5 36.  54.  29.  32.
 34.  52.  35.  41.  43. ]

 DATASET SHAPE
(518, 13)

 SUMMARY STATISTICS
       Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  Cholesterol (mg)  \
count         518.00             518.00         518.00            518.00
mean            8.89               4.21           0.01             28.27
std             9.35               4.14           0.07             47.72
min             0.00               0.00           0.00              0.00
25%             0.00               0.00           0.00              5.00
50%             6.00               3.50           0.00             15.00
75%            13.00               6.00           0.00             30.00
max            54.00              20.00           0.50            360.00

       Sodium (mg)  Carbs (g)  Fiber (g)  Protein (g)
count       518.00     518.00     518.00       518.00
mean        279.03      44.16       0.70         8.53
std         275.85      26.81       1.12         5.51
min           5.00       0.00       0.00         0.00
25%         115.00      32.00       0.00         5.00
50%         185.00      41.00       0.00         8.00
75%         320.00      56.00       1.00        11.00
max        1980.00     176.00       8.00        37.00

In [93]:
dnkn3.to_csv('dnkn_clean.csv', index=False)

In [94]:
dnkn4 = pd.read_csv('dnkn_clean.csv')
print(dnkn4.head())

           Category                                 Item  Calories  \
0  Cold Brew Coffee              Cold Brew Coffee, Large         5
1  Cold Brew Coffee             Cold Brew Coffee, Medium         5
2  Cold Brew Coffee              Cold Brew Coffee, Small         5
3  Cold Brew Coffee   Cold Brew Coffee with Cream, Large       120
4  Cold Brew Coffee  Cold Brew Coffee with Cream, Medium        90

   Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  Cholesterol (mg)  \
0            0.0                0.0            0.0                 0
1            0.0                0.0            0.0                 0
2            0.0                0.0            0.0                 0
3           12.0                6.0            0.0                35
4            9.0                4.5            0.0                25

   Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  Protein (g)  \
0           20          0          0           0            1
1           15          0          0           0            0
2           10          0          0           0            0
3           65          2          0           2            2
4           45          1          0           1            2

   Weight Watcher Pnts
0                  4.0
1                  5.0
2                  5.0
3                126.0
4                 93.5

In [95]:
print("First five rows of the reloaded dataframe 'dnkn4':")
print(dnkn4.head())

First five rows of the reloaded dataframe 'dnkn4':
           Category                                 Item  Calories  \
0  Cold Brew Coffee              Cold Brew Coffee, Large         5
1  Cold Brew Coffee             Cold Brew Coffee, Medium         5
2  Cold Brew Coffee              Cold Brew Coffee, Small         5
3  Cold Brew Coffee   Cold Brew Coffee with Cream, Large       120
4  Cold Brew Coffee  Cold Brew Coffee with Cream, Medium        90

   Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  Cholesterol (mg)  \
0            0.0                0.0            0.0                 0
1            0.0                0.0            0.0                 0
2            0.0                0.0            0.0                 0
3           12.0                6.0            0.0                35
4            9.0                4.5            0.0                25

   Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  Protein (g)  \
0           20          0          0           0            1
1           15          0          0           0            0
2           10          0          0           0            0
3           65          2          0           2            2
4           45          1          0           1            2

   Weight Watcher Pnts
0                  4.0
1                  5.0
2                  5.0
3                126.0
4                 93.5

In [ ]:
In Deliverable Two, the primary objective was to clean and prepare the Dunkin' Donuts nutritional dataset for analysis. Initially, the dataset contained several issues that could impede accurate statistical interpretation. These included the presence of duplicate records, which could lead to overcounting observations and special characters within numerical columns, such as "<5" and "\xa0" that prevented proper data type conversion and numerical operations. Additionally, some rows represented food categories rather than specific beverage products and there were empty string entries that needed to be treated as missing values. To address these issues, a systematic cleaning process was undertaken. Duplicate records were identified and removed. Special characters were systematically cleaned from relevant columns and empty strings were converted into NaN (Not a Number) values to be properly handled as missing data. Rows identified as food categories were filtered out to ensure that the dataset exclusively contained beverage items. Finally, all relevant columns were converted to appropriate numeric data types, and the entire dataset was validated through summary statistics, data type checks, and shape verification to ensure it was clean, consistent, and ready for further analysis.